name: Run screenshot bot to images in docs

on:
  push:

jobs:
  run-screenshot-bot:
    env:
      RAILS_ENV: "develop"
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mariadb
        env:
          MYSQL_DATABASE: "dodona"
          MYSQL_ROOT_PASSWORD: "dodona"
          MYSQL_HOST: "localhost"
        ports:
        - 3000:3000
        options: --health-cmd "mysqladmin ping --silent" --health-interval 10s --health-timeout 10s --health-retries 6
    steps:
      - uses: actions/checkout@v2
      - name: Use Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.6
      - name: Check Ruby version
        run: ruby -v

      - name: Clone devolop branch of Dodona
        uses: actions/checkout@master
        with:
          repository: dodona-edu/dodona
          ref: "bot-branch"

      - name: Run bundle
        run: |
          gem install bundler:2.1.4
          bundle install

      - name: Seed database
        run: |
          submissions=$(bundle exec rake db:seed | tail -n 1)
          ./bin/server

      - shell: bash
        run: |
          echo "$PATH"
          ls -a
        
      - name: Install and take screenshots
        run: |
          cd screenshot-bot
          yarn install
          echo submissions | yarn run run
